title: Dmitry Mikhailenko
email: dmitry@mikhailenko.net
author:
  email: dmitry@mikhailenko.net
description: >-

baseurl: ""
url: "mikhdm.github.io"
github_username: mikhdm

remote_theme: jekyll/minima@b3385fe

plugins:
  - jekyll-seo-tag

minima:
  skin: solarized-light
  nav_pages:
    - contacts.md
  social_links:
    - url: https://github.com/mikhdm
      title: GitHub
      icon: square-github
    - url: https://linkedin.com/in/mikhdm
      title: LinkedIn
      icon: square-linkedin
  hide_site_feed_link: true
