title: Dmitry Mikhailenko
email: d@mikhailenko.net
author:
  email: d@mikhailenko.net
description: >-

baseurl: ""
url: "mikhdm.github.io"
github_username: mikhdm

remote_theme: jekyll/minima@1fe0fbf

minima:
  skin: solarized-light
  nav_pages:
    - resume.md
    - contact.md
  social_links:
    - url: https://github.com/mikhdm
      title: GitHub
      icon: square-github
    - url: https://linkedin.com/in/mikhdm
      title: LinkedIn
      icon: square-linkedin
  hide_site_feed_link: true
