title: Dmitry Mikhailenko
email: d@mikhailenko.net
author:
  email: d@mikhailenko.net
description: >-

baseurl: ""
url: "mikhdm.github.io"
github_username: mikhdm

theme: minima

minima:
  skin: solarized-light
  nav_pages:
    - about.md
    - contact.md
  social_links:
    - url: https://github.com/mikhdm
      title: GitHub
    - url: https://linkedin.com/in/mikhdm
      title: LinkedIn
